# Generated by Django 4.2.4 on 2023-09-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_like_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LIke_post',
            new_name='LikePost',
        ),
    ]
